= Meeting 07-14-2015

== Participants
Jean Noel, Danaelle Puechmaille, François, Martin, Juan

== Examples and tutorials. 

Sent by François and available at link:https://docs.google.com/document/d/1TRVCUd6eVZj5UXehl-rttnvbNSe3pmHe9zJfXCqUqrI/edit[DOCS]

== FA-DTTS

Statistical methods Functional Analysis of Diffusion Tensor (FADTTS) - It is written in matlab. 
Available at link:https://www.nitrc.org/projects/fadtts[NITRC]

=== Objectives

1. Create a GUI that provides an interface to MATLAB. 
The c++ program will call the matlab scripts from FADTTS.
2. The interface should provide the fields to input clinical data and/or demographic data. 
3. The plotting facilities could all be exported to MATLAB (for now). 
3.1 The idea will be to use other plotting tools such as Qtplot, python, R, etc.

== Connectivity toolbox

Probabilistic tractography.
The output of a probabilistic tractography algorithm is a connectivity matrix. 

=== Objectives

1. Wrapper of the connectivity tool available in  FSL - toolbox for probabilistic tractography, statistical analysis. 
1.1 The tool uses MATLAB scripts to calculate the connectivity among brain regions. 
1.2 The cortical surface is projected onto a sphere and a regular random subdivision is done on the spherical surface. 
1.3 The connectivity is then calculated on the subdivided sphere (Input to FSL connectivity tool).
1.4 The TRUE connectivity map is calculated after a number of iterations. 
2. Create a tool that allows multiple analysis of the connected regions. 
3. Optimize the algorithm.


== Slicer training session. 

August 5th - Visitor from Texas A&M (TAMU).

== Next image lunch (Monday 12:00)
IPMI recap by Martin. Genetic data applied to imaging data. 
